[package]
name = "calculator"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
publish = false

[workspace]

[lib]
name = "calculator"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "calculator"
path = "src/main.rs"

[dependencies]
rustferry = { package = "rustferry", version = "=0.1.0", path = "../../crates/rustferry", default-features = false, features = [] }
slint = { version = "=1.17.1", default-features = false, features = ["std", "compat-1-2", "backend-winit", "backend-android-activity-06", "renderer-skia"] }
thiserror = "2.0"

[lints.rust]
unsafe_code = "deny"
