[package]
name = "rustferry-worker-macos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Hardened macOS build and signing worker for RustFerry"

[[bin]]
name = "ferry-worker-macos"
path = "src/main.rs"

[dependencies]
camino.workspace = true
cap-std.workspace = true
clap.workspace = true
fs2.workspace = true
plist.workspace = true
rustferry-apple = { version = "0.1.0", path = "../rustferry-apple" }
rustferry-core = { version = "0.1.0", path = "../rustferry-core" }
rustferry-remote = { version = "0.1.0", path = "../rustferry-remote" }
same-file.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
toml.workspace = true
uuid.workspace = true
zip.workspace = true

[lints]
workspace = true
